#!/bin/bash
# 0x0 - client for 0x0.st

me=${0##*/}
host=https://up.simo.sh

if [[ ! -t 1 ]];then
    quiet=true
fi

help() {
    cat >&2 <<EOF
Usage: ${me} [-f <file>] [-s <url>] [-u <url>] [file]

Client for interacting with up.simo.sh

If no file is given, upload stdin.

    -f <file>       - upload <file>
EOF
}

function clip {
    if command -v xsel >/dev/null 2>&1;then
        printf '%s' "$@" | xsel -b
    fi
}

function file_upload {
    local curl_opts="-s" file="$1" type
    [[ "${progress_quiet}" ]] || curl_opts="-#"
    [[ "${quiet}" ]] || printf "uploading \"%s\"...\n" "${file}" >&2
    [[ "$#" -gt 1 ]] && printf "%s ... " "${url}"
    url=$(curl ${curl_opts} -F "file=@${file}" "${host}" -n)
    printf '%s' "${url}"
    [ -t 1 ] && printf '\n'
    clip "${url}"
}

# 1KiB = 1024 bytes
# 1MiB = 1024 KiB
# max size - 256MiB

max_size=$(( (1024*1024) * 256 ))

if [[ -f "$1" || "$#" -lt 1 ]];then
    mode="default"
else
    mode="$1"
    shift
fi

case "$mode" in
    default)
        if [[ "$#" -gt 0 ]];then
            file_upload "${@}"
        else
            cat | quiet=true file_upload "/dev/stdin"
        fi
    ;;
    -f)
        file_upload "${@}"
    ;;
    -h|--help)
        help
    ;;
esac

